backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
media_folder: static/img
public_folder: /img
collections:
  - name: 'blog' #using inroot
    label: '部落格' #UI to see
    folder: 'content/blog' #file origin
    create: true
    editor:
      preview: false
    fields:
      - { label: '標題', name: 'title', widget: 'string' }
      - { label: '發布日期', name: 'date', widget: 'datetime', required: false }
      - { label: '描述', name: 'description', widget: 'string' }
      - { label: '文章類型', name: 'type', widget: 'string',hint: 'post or featured' }
      - { label: '圖片', name: 'image', widget: 'image' }
      - { label: '標籤', name: 'categories', widget: 'list',hint: '使用逗號隔開' }
      - { label: '內容', name: 'body', widget: 'markdown' }
  - name: 'main' #using inroot
    label: '主要檔案' #UI to see
    folder: 'content' #file origin
    create: true
    editor:
      preview: false
    fields:
      - { label: '標題', name: 'title', widget: 'string' }
      - { label: '發布日期', name: 'date', widget: 'datetime', required: false }
      - { label: '描述', name: 'description', widget: 'string' }
      - { label: '圖片', name: 'image', widget: 'image', required: false  }
      - { label: '標籤', name: 'categories', widget: 'list',hint: '使用逗號隔開', required: false }
      - { label: '內容', name: 'body', widget: 'markdown' , required: false }